# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|


  ssh_pub_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOK99l9c6rGcoV7oZBBEJ+xYgcgpwoj4DbepPEQ3LWqT3go5dIRmfx3wdHtCw9dvL6nGHRRdxgFQVQF1+SWnny3F2VnhN3c7z5PD4s7ugrAHIrHyy7a9nlsHz1FS0f5WbMOdwPysDQsegpqYAz/3tvTzlEtnBitVHJrJw1mh7pO8ZrhsUiPvspBOAQvROVFLTY1tGR4rZ5Kz9cMvSn/rNQ2L8NY8SiAu5RnoycbHksig4YpRYHdLvp6WO1AbCZy4UFKSpPr6WGus/iOwG83+dcnR18Zlv9+ZUC91k+wFGezQkIjdMjUP/6ki3XJUICfrcExdDsSoKOPB2DPRn4eawH root@wisgndt86"
  config.vm.box = "generic/ubuntu1804"
  config.vm.provider "libvirt" do |v|
    v.memory = 8192
    v.cpus = 3
  end

  config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys"

  config.vm.post_up_message = "Up and running!"
  
  config.vm.define "west1" do |west1|
    west1.vm.hostname = "west1"
    west1.vm.network :public_network, :ip => "10.243.28.50", :dev => "br0", :mode => "bridge", :bridge => "br0"
  end
  
  config.vm.define "west2" do |west2|
    west2.vm.hostname = "west2"
    west2.vm.network :public_network, :ip => "10.243.28.51", :dev => "br0", :mode => "bridge", :bridge => "br0"
  end
  
  config.vm.define "west3" do |west3|
    west3.vm.hostname = "west3"
    west3.vm.network :public_network, :ip => "10.243.28.52", :dev => "br0", :mode => "bridge", :bridge => "br0"
  end

  config.vm.define "west4" do |west4|
    west4.vm.hostname = "west4"
    west4.vm.network :public_network, :ip => "10.243.28.53", :dev => "br0", :mode => "bridge", :bridge => "br0"
  end

   config.vm.define "east1" do |east1|
    east1.vm.hostname = "east1"
    east1.vm.network :public_network, :ip => "10.243.28.60", :dev => "br0", :mode => "bridge", :bridge => "br0"
  end
  
  config.vm.define "east2" do |east2|
    east2.vm.hostname = "east2"
    east2.vm.network :public_network, :ip => "10.243.28.61", :dev => "br0", :mode => "bridge", :bridge => "br0"
  end
  
  config.vm.define "east3" do |east3|
    east3.vm.hostname = "east3"
    east3.vm.network :public_network, :ip => "10.243.28.62", :dev => "br0", :mode => "bridge", :bridge => "br0"
  end

  config.vm.define "east4" do |east4|
    east4.vm.hostname = "east4"
    east4.vm.network :public_network, :ip => "10.243.28.63", :dev => "br0", :mode => "bridge", :bridge => "br0"
  end
end

