apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "resourcename" . }}
type: Opaque
data:
  {{- range $key, $value := (index .Values.secrets .Release.Namespace) }}
  {{ $key }}: {{ $value }}
  {{- end }}